/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 03-фев-2016 7:50:04 				*/
/*  DBMS       : SQLite 								*/
/* ---------------------------------------------------- */

DROP TABLE IF EXISTS 'Requests'
;

DROP TABLE IF EXISTS 'dicInsideAccountPosition'
;

DROP TABLE IF EXISTS 'dicBalanceAccounts'
;

DROP TABLE IF EXISTS 'BalanceInfo'
;

DROP TABLE IF EXISTS 'ApplicationAccount'
;

-- Информация по запросам информации по счетам
CREATE TABLE 'Requests'
(
	'ID' INTEGER NOT NULL PRIMARY KEY,
	'RequestDate' TEXT NOT NULL, -- Дата запроса
	'Status' INTEGER NOT NULL, -- Статус запроса
	'BalanceAccountId' INTEGER NOT NULL -- Идентификационный номер счета, для которого выполнялся запрос
)
;

-- Справочник отдельных позиций счета
CREATE TABLE 'dicInsideAccountPosition'
(
	'ID' INTEGER NOT NULL PRIMARY KEY, -- !!! Этот же идентификационный номер определяет отдельную позицию счета (совпадает) в таблице InsideAccountPositions  (поле ID) на сервере !!!
	'Name' TEXT NOT NULL -- Текстовое имя отдельной позиции счета
)
;

-- Спраочник счетов
CREATE TABLE 'dicBalanceAccounts'
(
	'ID' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, -- !!! Этот же идентификационный номер определяет счет (совпадает) в таблице BalanceAccount  (поле ID) на сервере !!!
	'Name' TEXT NOT NULL -- Текстовое имя счета
)
;

-- Содержит последние данные по состоянию счетов
CREATE TABLE 'BalanceInfo'
(
	'ID' INTEGER NOT NULL PRIMARY KEY,
	'BalanceAccountId' INTEGER NOT NULL, -- Идентификационный номер счета
	'InsideAccountPositionId' INTEGER NOT NULL, -- Идентификационный номер отдельной позиции счета
	'InsideAccountPositionValue' TEXT NOT NULL, -- Значение отдельной позиции счета
	'RequestId' INTEGER NOT NULL, -- Запрос связанный с последним получением информации по счету

	CONSTRAINT 'FK_BalanceInfo_Requests' FOREIGN KEY ('RequestId') REFERENCES 'Requests' ('ID') ON DELETE No Action ON UPDATE No Action
)
;

-- Содержит данные для входа в придложение
CREATE TABLE 'ApplicationAccount'
(
	'ID' INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	'Login' TEXT NOT NULL, -- Имя пользователя
	'Password' TEXT NOT NULL, -- Пароль для входа в приложение
	'EditDate' TEXT NOT NULL -- Дата последнегоо изменения
)
;

CREATE INDEX 'IXFK_BalanceInfo_Requests'
 ON 'BalanceInfo' ('RequestId' ASC)
;
